str = ''
str += '<div id="footer">'
str += '	<div class="footer-wrap clear">'
str += '		<div class="f_both">'
str += '			<div class="l_logo"><a href="#"><img src="./img/common/footer_logo.png" alt="대전창조경제혁신센터"></a></div>'
str += '			<div class="info">'
str += '				<p>대전광역시 유성구 대학로 291 KAIST 나노종합기술원 9층</p>'
str += '				<ul class="add">'
str += '					<li>TEL : <a href="tel:042-385-0532">042-385-0532</a><span class="bar"></span></li>'
str += '					<li>E-Mail : skdd@sk.com</li>'
str += '				</ul>'
str += '				<p>COPYRIGHT (재)대전창조경제혁신센터 ALL RIGHTS RESERVED.</p>'
str += '			</div>'
str += '		</div>'
str += '		<div class="r_logo"><a href="#"><img src="./img/common/sk.png" alt="SK"></a></div>'
str += '	</div>'
str += '</div>'

document.write(str);