str = ''
str += '<div id="header">'
str += ''
str += '	<div class="h_group">'
str += ''
str += '		<div>'
str += '			<h1>'
str += '				<a href="index.html"><img src="img/common/logo.png" alt="기술사업화 Market Place" /></a>'
str += '			</h1>'
str += '			<div id="gnb">'
str += '				<button type="button" class="btn_menu"><span class="blind">전체메뉴 열기</span></button>'
str += '				<div class="box">'
str += '					<button type="button" class="btn_close"><span class="blind">전체메뉴 닫기</span></button>'
str += '					<ul>'
str += '						<li><a href="#">서비스안내<span class="gnb_border"></span></a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="sub.html">기술사업화MP 소개</a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="#">기술이전<span class="gnb_border"></span></a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="sub.html">유망기술 검색</a></li>'
str += '									<li><a href="sub.html">수요기술 이전</a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="#">SK사업제안<span class="gnb_border"></span></a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="#">사업 및 서비스제안</a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="#">벤처기업정보<span class="gnb_border"></span></a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="#">SK지원벤처 소개</a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="#">대전창조포럼<span class="gnb_border"></span></a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="#">포럼발표 신청</a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '					</ul>'
str += '				</div>'
str += '			</div>'
str += '			<div class="search_area">'
str += '				<div class="sizing_wrap">'
str += '					<form method="post" name="" action="">'
str += '						<fieldset>'
str += '							<legend>검색</legend>'
str += '							<input type="text" name="" id="inp_search" placeholder="검색어를 입력하세요">'
str += '							<a href="javascript:" class="btn_search"><i class="ico ico_search">검색</i></a>'
str += '							<a href="javascript:" class="btn_cl"><i class="ico ico_cl">검색 닫기</i></a>'
str += '						</fieldset>'
str += '					</form>'
str += '				</div>'
str += '			</div>'
str += '		</div>'
str += ''
str += '	</div>'
str += ''
str += '</div>'

document.write(str);