str = ''
str += '<div id="header">'
str += ''
str += '	<div class="h_group">'
str += ''
str += '		<div>'
str += '			<h1>'
str += '				<a href="index.html"><img src="img/common/logo.png" alt="기술사업화 Market Place" /></a>'
str += '			</h1>'
str += '			<div id="gnb">'
str += '				<button type="button" class="btn_menu">전체메뉴 열기</button>'
str += '				<div class="box">'
str += '					<button type="button" class="btn_close">전체메뉴 닫기</button>'
str += '					<ul>'
str += '						<li><a href="#"><span>서비스안내</span><span class="gnb_border"></span></a>'
str += '							<div class="sub_menu">'
str += '								<div class="inner">'
str += '									<ul>'
str += '										<li><a href="sub.html"><span>기술사업화MP 소개</span></a></li>'
str += '									</ul>'
str += '								</div>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="#"><span>기술이전</span><span class="gnb_border"></span></a>'
str += '							<div class="sub_menu">'
str += '								<div class="inner">'
str += '									<ul>'
str += '										<li><a href="sub.html"><span>유망기술 검색</span></a></li>'
str += '										<li><a href="sub.html"><span>수요기술 이전</span></a></li>'
str += '									</ul>'
str += '								</div>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="#"><span>SK사업제안</span><span class="gnb_border"></span></a>'
str += '							<div class="sub_menu">'
str += '								<div class="inner">'
str += '									<ul>'
str += '										<li><a href="#"><span>사업 및 서비스제안</span></a></li>'
str += '									</ul>'
str += '								</div>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="#"><span>벤처기업정보</span><span class="gnb_border"></span></a>'
str += '							<div class="sub_menu">'
str += '								<div class="inner">'
str += '									<ul>'
str += '										<li><a href="#"><span>SK지원벤처 소개</span></a></li>'
str += '									</ul>'
str += '								</div>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="#"><span>대전창조포럼</span><span class="gnb_border"></span></a>'
str += '							<div class="sub_menu">'
str += '								<div class="inner">'
str += '									<ul>'
str += '										<li><a href="#"><span>포럼발표 신청</span></a></li>'
str += '									</ul>'
str += '								</div>'
str += '							</div>'
str += '						</li>'
str += '					</ul>'
str += '				</div>'

str += '				<div class="util-menu">'
str += '					<div class="keyword">'
str += '						<form name="" method="post" action="">'
str += '							<fieldset>'
str += '								<legend>검색</legend>'
str += '								<input type="text" title="검색어를 입력하세요" placeholder="검색어를 입력하세요">'
str += '								<a href="javascript:" class="util"><i class="ico ico_zoom"><span class="blind">검색</span></i></a>'
str += '								<a href="javascript:" class="btn-cl-search"><i>검색 닫기</i></a>'
str += '							</fieldset>'
str += '						</form>'
str += '					</div>'
str += '				</div>'

str += '			</div>'
str += '		</div>'
str += ''
str += '	</div>'
str += ''
str += '</div>'

document.write(str);